- name: Configure App
  hosts: app
  # tags: app-tag  <-- Тэг нам больше не нужен
  become: true
  vars:
   db_host: 10.132.0.2
  tasks:
    - copy: src=files/puma.service dest=/etc/systemd/system/puma.service
      notify: reload puma
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
    - systemd: name=puma enabled=yes
  handlers:
    - systemd: name=puma state=restarted
