Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end
config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.hostname = "dbserver"
    config.vm.network "private_network", ip: "10.10.20.10" ,virtualbox__intnet: "mynetwork"
    db.vm.provision "ansible" do |ansible| 
    ansible.playbook = "playbooks/site.yml" 
    ansible.groups = {
	"db" => ["dbserver"],
	"db:vars" => {"mongo_bind_ip" => "0.0.0.0"} 
	}
	end
  	end
  
  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    config.vm.network "private_network", ip: "10.10.10.20",mask:"255.255.255.0" ,virtualbox__intnet: "mynetwo1rk"
    app.vm.provision "ansible" do |ansible| ansible.playbook = "site.yml" ansible.groups = {
	"app" => ["appserver"],
	"app:vars" => { "db_host" => "10.10.20.10"}
	}
	end
 	end
end
